static const char* cl_codus = "constant char b2c[2] = \"-'\";"
"kernel void viol(global uchar* in, global uchar8* out) {"
"    size_t i = get_global_id(0);"
""
"    out[i].s0 = b2c[in[i] >> 7 & 1];"
"    out[i].s1 = b2c[in[i] >> 6 & 1];"
"    out[i].s2 = b2c[in[i] >> 5 & 1];"
"    out[i].s3 = b2c[in[i] >> 4 & 1];"
"    out[i].s4 = b2c[in[i] >> 3 & 1];"
"    out[i].s5 = b2c[in[i] >> 2 & 1];"
"    out[i].s6 = b2c[in[i] >> 1 & 1];"
"    out[i].s7 = b2c[in[i]      & 1];"
"}"
""
"kernel void unviol(global uchar8* in, global uchar* out) {"
"    size_t i = get_global_id(0);"
""
"    out[i]  = (bool)(in[i].s0 ^ 45) << 7;"
"    out[i] |= (bool)(in[i].s1 ^ 45) << 6;"
"    out[i] |= (bool)(in[i].s2 ^ 45) << 5;"
"    out[i] |= (bool)(in[i].s3 ^ 45) << 4;"
"    out[i] |= (bool)(in[i].s4 ^ 45) << 3;"
"    out[i] |= (bool)(in[i].s5 ^ 45) << 2;"
"    out[i] |= (bool)(in[i].s6 ^ 45) << 1;"
"    out[i] |= (bool)(in[i].s7 ^ 45);"
"}";